#!/bin/bash

# 1. Generate SSH Key
echo "Generating SSH key..."
ssh-keygen -t rsa -m PEM -f ~/.ssh/docker_agent_key -N "" <<< y >/dev/null 2>&1

# 2. Output the private key
echo "Private Key:-----------------"
cat ~/.ssh/docker_agent_key

# 3. Get the Group ID of the docker group of the host
DOCKER_GID=$(getent group docker | cut -d: -f3)

if [ -z "$DOCKER_GID" ]; then
        echo "Error getting host's docker group ID. Make sure Docker is installe                        d and running then try again."
        exit 1
else \
        echo ${DOCKER_GID}
fi

# 4. Build the Docker image
echo "Building Docker image..."

docker build --build-arg DOCKER_GID="${DOCKER_GID}" -t docker-agent-image .

# 5. Set the public key as environment variable
PUBLIC_KEY=$(cat ~/.ssh/docker_agent_key.pub)

# 6. Output the public key
echo "Public Key:------------------"
cat ~/.ssh/docker_agent_key.pub

# 7. Run the container with the public key
echo "Running Docker container on port 7777..."
docker run -td --privileged -p 7777:22 --name docker-agent -v /var/run/docker.so                        ck:/var/run/docker.sock \
       -e "JENKINS_AGENT_SSH_PUBKEY=${PUBLIC_KEY}" docker-agent-image && echo "J                        enkins Docker agent started."
