# Use the Jenkins SSH agent as the base image
FROM jenkins/ssh-agent:alpine-jdk17

# Switch to the root user to install Docker and other services
USER root

# Install Docker
RUN apk update
RUN apk add --update docker

# Create the docker group (in case it's not created by default) and add jenkins to it
RUN addgroup jenkins docker

# Switch back to the Jenkins user
USER jenkins

# Start Docker daemon in the background and keep the container running
CMD ["sh", "-c", "dockerd & sleep 5 && tail -f /dev/null"]
