# Use the Jenkins SSH agent as the base image
FROM jenkins/ssh-agent:alpine-jdk17

# Switch to the root user to install Docker
USER root

# Install Docker
RUN apk update && \
    apk add --no-cache docker

# Create add jenkins user to the docker group
RUN addgroup jenkins docker

# Switch back to the jenkins user
USER jenkins

# Expose port 22 for SSH
EXPOSE 22

# Start Docker daemon in the background and keep the container running
CMD ["sh", "-c", "dockerd & sleep 5 && tail -f /dev/null"]
